local ReplicatedStorage = game:GetService("ReplicatedStorage")

local UILib = require(ReplicatedStorage.UILib)

local window = UILib:CreateWindow({
	Title = "PixlLib",
})

window:createTab("Home", 15637356511)
window:createTab("Settings", 15637356511)
window:createTab("About", 15637356511)
window:createTab("Info", 16089599792)
window:createTab("Eggs", 15637367451)
window:createTab("Farming", 16093555964)
window:createTab("Settings", 87867412432006)
window:createTab("Player", 15637355840)
window:createTab("Upgrades", 16089599792)
window:createTab("Fishing", 16093555964)
window:createTab("Mailbox", 15637375511)
window:createTab("Quests", 15637359494)
window:createTab("Automatic", 15637369009)
window:createTab("Webhook", 122219359034661)
window:createTab("Statistics", 94231924171549)
window:createTab("Optimisation", 94231924171549)
window:createTab("Shop", 16093555964)
